regions:
  - us-east-1
  - global
  - ap-southeast-1

account-blocklist:
  - "999999999999" # production

feature-flags:
  disable-deletion-protection:
    RDSInstance: true
    EC2Instance: true
    CloudformationStack: true
  force-delete-lightsail-addons: true

# Add account to nuke
accounts:
  "REPLACE_ACCOUNT_ID": #temporary aws sandbox account
    filters:
      IAMRole:
        - "CspmMonitorAws"
        - "OrganizationAccountAccessRole"
        - "AWSServiceRoleForSSO"
        - "AWSServiceRoleForSupport"
        - "AWSServiceRoleForTrustedAdvisor"
        - "AWSCloudFormationStackSetExecutionRole"
        - "AWSServiceRoleForAmazonGuardDuty"
        - "AWSServiceRoleForAmazonGuardDutyMalwareProtection"
        - "AWSServiceRoleForCloudTrail"
        - "cldcvr-github-runner-role"
        - "CloudWatch-CrossAccountSharingRole"
        - "custodian-role"
        - "cc-access"
        - type: glob
          value: "StackSet-AutoTag-*"
        - type: glob
          value: "AWSReservedSSO_AdministratorAccess_*"
        - type: glob
          value: "AWSReservedSSO_*"
        - type: glob
          value: "DefenderForCloud-*"
        - type: glob
          value: "azuredefender-*"
        - type: glob
          value: "cc-prod-*"
      IAMInstanceProfile:
        - "cc-prod-ssm-run-command-role"
      IAMInstanceProfileRole:
        - type: glob
          value: "cc-prod-ssm-run-command-role*"
      IAMRolePolicyAttachment:
        - "OrganizationAccountAccessRole -> AdministratorAccess"
        - "AWSServiceRoleForOrganizations -> AWSOrganizationsServiceTrustPolicy"
        - "AWSServiceRoleForSSO -> AWSSSOServiceRolePolicy"
        - "AWSServiceRoleForSupport -> AWSSupportServiceRolePolicy"
        - "AWSServiceRoleForTrustedAdvisor -> AWSTrustedAdvisorServiceRolePolicy"
        - "AWSReservedSSO_AdministratorAccess_* -> AdministratorAccess"
        - "AWSCloudFormationStackSetExecutionRole -> AdministratorAccess"
        - "cc-prod-ssm-run-command-role -> AmazonEC2RoleforSSM"
        - "cc-prod-ssm-run-command-role -> AmazonSSMManagedInstanceCore"
        - "cc-prod-ssm-run-command-role -> AmazonEC2ReadOnlyAccess"
        - "cc-prod-ssm-run-command-role -> startAutomationAndCommandPermissions"
        - "cldcvr-github-runner-role -> AdministratorAccess"
        - "custodian-role -> AdministratorAccess"
        - type: glob
          value: "AWSReservedSSO_AdministratorAccess_* -> AdministratorAccess"
        - type: glob
          value: "cc-prod-ssm-run-command-role*"
      IAMRolePolicy:
        - "cc-prod-ssm-run-command-role -> startAutomationAndCommandPermissions"
      EC2DHCPOption:
        - type: glob
          value: "*"
      CloudTrailTrail:
        - "cldcvr-org-cloudtrail-us-east-1"
        - "cloudcover-sg-org-cloudtrail"
      CloudWatchEventsTarget:
        - type: glob
          value: "Rule: AutoScalingManagedRule*"
      CloudWatchEventsRule:
        - type: glob
          value: "Rule: AutoScalingManagedRule"
      CloudWatchLogsLogGroup:
        - "/aws/lambda/AutoTag"
        - type: glob
          value: "/aws/lambda/StackSet-iam-password-*"
      LambdaFunction:
        - AutoTag
      CloudFormationStack:
        - type: glob
          value: "StackSet-*"
      IAMSAMLProvider:
        - type: glob
          value: "arn:aws:iam::*:saml-provider/AWSSSO_*"
      IAMOpenIDConnectProvider:
        - type: glob
          value: "arn:aws:iam::*:oidc-provider/sts.windows.net/*"
      GuardDutyDetector:
        - type: glob
          value: "*"
      SecurityHub:
        - type: glob
          value: "*"
