# gitleaks.toml

[[rules]]
description = "AWS"
id = "aws-access-token"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
keywords = [
    "akia","agpa","aida","aroa","aipa","anpa","anva","asia",
]

[[rules]]
description = "AWS Secret Key"
id = "aws-secret-key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
tags = ["key", "AWS"]

[[rules]]
description = "Azure SAS"
id = "azure-sas"
regex = '''https://(\\w+\\.){1,}(blob|dfs|file|queue|table).core.windows.net/[^?]*\?sv'''
tags = ["key", "Azure"]

[[rules]]
description = "Google Cloud Platform API key"
id = "gcp-api-key"
regex = '''AIza[0-9A-Za-z\\-_]{35}'''
tags = ["key", "GCP"]

[[rules]]
description = "Google OAuth"
id = "google-oauth"
regex = '''ya29\.[0-9A-Za-z\\-_]+'''
tags = ["key", "GCP"]

[[rules]]
description = "Heroku API key"
id = "heroku-api-key"
regex = '''(?i)heroku(.{0,20})?['"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{12}['"]'''
tags = ["key", "Heroku"]

[[rules]]
description = "Docker config"
id = "docker-config"
regex = '''"auths"\\s*:\\s*{\\s*".*?"\\s*:\\s*{\\s*"auth"\\s*:\\s*"'''
tags = ["key", "Docker"]

[[rules]]
description = "Private key"
id = "private-key"
regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
tags = ["key", "SSH"]

[[rules]]
description = "Jenkins"
id = "jenkins-private-key"
regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
tags = ["key", "Jenkins"]

[[rules]]
description = "Facebook Access Token"
id = "facebook-access-token"
regex = '''EAACEdEose0cBA[0-9A-Za-z]+'''
tags = ["key", "Facebook"]

[[rules]]
description = "GitHub Token"
id = "github-token"
regex = '''ghp_[0-9A-Za-z]{36}'''
tags = ["key", "GitHub"]

[[rules]]
description = "Google API Key"
id = "google-api-key"
regex = '''AIza[0-9A-Za-z\\-_]{35}'''
tags = ["key", "Google"]

[[rules]]
description = "Twitter Access Token"
id = "twitter-access-token"
regex = '''[1-9][ 0-9]+-.*'''
tags = ["key", "Twitter"]

[[rules]]
description = "Twitter Secret Key"
id = "twitter-secret-key"
regex = '''[0-9a-z]{35,44}'''
tags = ["key", "Twitter"]

[[rules]]
description = "LinkedIn Client ID"
id = "linkedin-client-id"
regex = '''[0-9a-z]{12}'''
tags = ["key", "LinkedIn"]

[[rules]]
description = "LinkedIn Secret Key"
id = "linkedin-secret-key"
regex = '''[0-9a-z]{16}'''
tags = ["key", "LinkedIn"]

[[rules]]
description = "Slack"
id = "slack-token"
regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''
tags = ["key", "Slack"]

[[rules]]
description = "Asymmetric Private Key"
id = "asymmetric-private-key"
regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
tags = ["key", "Asymmetric"]

[[rules]]
description = "Generic Secret"
id = "generic-secret"
regex = '''(?i)secret(.{0,20})?['\"][0-9a-zA-Z]{32,45}['\"]'''
tags = ["key", "Secret"]

[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)api(.{0,20})?['\"][0-9a-zA-Z]{32,45}['\"]'''
tags = ["key", "API"]

[[rules]]
description = "Possible Hash"
id = "possible-hash"
regex = '''[a-f0-9]{32,64}'''
tags = ["key", "Hash"]
